# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/droncuadam/kodabasla/DroneAppStore.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(963, 469)
        MainWindow2.setStyleSheet("\n"
"background-color: rgb(167, 167, 167);\n"
"alternate-background-color: rgb(85, 0, 0);\n"
"selection-background-color: rgb(170, 255, 127);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 971, 541))
        self.scrollArea.setStyleSheet("color: rgb(107, 102, 248);\n"
"selection-color: rgb(170, 170, 255);\n"
"border-top-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 969, 539))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(390, 40, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.log = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.log.setGeometry(QtCore.QRect(20, 320, 931, 111))
        self.log.setSizeIncrement(QtCore.QSize(0, 0))
        self.log.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.log.setFont(font)
        self.log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.log.setLineWidth(1)
        self.log.setAutoScrollMargin(16)
        self.log.setRowCount(1)
        self.log.setObjectName("log")
        self.log.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.log.setItem(0, 3, item)
        self.log.horizontalHeader().setDefaultSectionSize(220)
        self.log.horizontalHeader().setMinimumSectionSize(50)
        self.dronesec = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.dronesec.setGeometry(QtCore.QRect(340, 90, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dronesec.setFont(font)
        self.dronesec.setStyleSheet("")
        self.dronesec.setObjectName("dronesec")
        self.dronesec.addItem("")
        self.startmission = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.startmission.setGeometry(QtCore.QRect(340, 240, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.startmission.setFont(font)
        self.startmission.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(107, 102, 248);")
        self.startmission.setObjectName("startmission")
        self.stopmission = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.stopmission.setGeometry(QtCore.QRect(510, 240, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.stopmission.setFont(font)
        self.stopmission.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.stopmission.setObjectName("stopmission")
        self.secilenurunlabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.secilenurunlabel.setGeometry(QtCore.QRect(690, 179, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.secilenurunlabel.setFont(font)
        self.secilenurunlabel.setText("")
        self.secilenurunlabel.setObjectName("secilenurunlabel")
        self.urunsec = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.urunsec.setGeometry(QtCore.QRect(340, 170, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.urunsec.setFont(font)
        self.urunsec.setStyleSheet("color: rgb(107, 102, 248);\n"
"background-color: rgb(225, 225, 225);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"")
        self.urunsec.setObjectName("urunsec")
        self.chance_drone = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.chance_drone.setGeometry(QtCore.QRect(690, 90, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chance_drone.setFont(font)
        self.chance_drone.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(107, 102, 248);")
        self.chance_drone.setObjectName("chance_drone")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.actionGiri = QtWidgets.QAction(MainWindow2)
        self.actionGiri.setObjectName("actionGiri")
        self.actionHesaplar_Ekle = QtWidgets.QAction(MainWindow2)
        self.actionHesaplar_Ekle.setObjectName("actionHesaplar_Ekle")
        self.actionBot_Ba_lar = QtWidgets.QAction(MainWindow2)
        self.actionBot_Ba_lar.setObjectName("actionBot_Ba_lar")
        self.actionGiri_2 = QtWidgets.QAction(MainWindow2)
        self.actionGiri_2.setObjectName("actionGiri_2")
        self.actionHesap_Ekle = QtWidgets.QAction(MainWindow2)
        self.actionHesap_Ekle.setObjectName("actionHesap_Ekle")
        self.actionBot_Ba_lat = QtWidgets.QAction(MainWindow2)
        self.actionBot_Ba_lat.setObjectName("actionBot_Ba_lat")

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow"))
        self.label.setText(_translate("MainWindow2", "DroneAppStore  v 4.0.0"))
        item = self.log.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow2", "Drone"))
        item = self.log.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow2", "App"))
        item = self.log.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow2", "UPDATE DATE"))
        item = self.log.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow2", "STATUS"))
        __sortingEnabled = self.log.isSortingEnabled()
        self.log.setSortingEnabled(False)
        item = self.log.item(0, 0)
        item.setText(_translate("MainWindow2", "-"))
        item = self.log.item(0, 1)
        item.setText(_translate("MainWindow2", "-"))
        item = self.log.item(0, 2)
        item.setText(_translate("MainWindow2", "-"))
        item = self.log.item(0, 3)
        item.setText(_translate("MainWindow2", "-"))
        self.log.setSortingEnabled(__sortingEnabled)
        self.dronesec.setItemText(0, _translate("MainWindow2", "Select Drone"))
        self.startmission.setText(_translate("MainWindow2", "Start Mission"))
        self.stopmission.setText(_translate("MainWindow2", "Stop Mission"))
        self.urunsec.setText(_translate("MainWindow2", "Select Product"))
        self.chance_drone.setText(_translate("MainWindow2", "Chance Drone"))
        self.actionGiri.setText(_translate("MainWindow2", "Giriş"))
        self.actionHesaplar_Ekle.setText(_translate("MainWindow2", "Hesapları Ekle"))
        self.actionBot_Ba_lar.setText(_translate("MainWindow2", "Bot Başlat"))
        self.actionGiri_2.setText(_translate("MainWindow2", "Giriş"))
        self.actionHesap_Ekle.setText(_translate("MainWindow2", "Hesap Ekle"))
        self.actionBot_Ba_lat.setText(_translate("MainWindow2", "Bot Başlat"))

